#!/usr/bin/env python

# lightwriter -- serial testing script
# copyleft 2007-2009 ricardo lafuente
# 
# script for testing serial communication with an arduino
# running the lightwriter.cpp program
# 
# just connect the board through USB and run this.

import serial
from time import sleep

ser = serial.Serial('/dev/ttyUSB0', 9600, timeout=1)

ser.flushInput()
ser.flushOutput()

while 1:
    ser.write('2')
    token = ser.readline().strip()
    if token == "2":
        print "Woohoo! Serial comm is working!"
        break
    else:
        print "Token is " + token + ", wtf?"


'''  
#   if not token:
    if (token[0] == "2"):
        print "Serial communication is working!"
        break
    else:
        continue
        print "Retrying"
        tries = tries + 1
        if tries > maxtries:
            print "No communication"
            break
'''
